"""empty message

Revision ID: 254868bdd4da
Revises: 6861573016ff
Create Date: 2022-06-26 16:08:37.350403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254868bdd4da'
down_revision = '6861573016ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'unread')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('unread', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
