"""empty message

Revision ID: 6861573016ff
Revises: 22c224d53cd9
Create Date: 2022-06-26 15:45:18.478162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6861573016ff'
down_revision = '22c224d53cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_unread_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_unread_time')
    # ### end Alembic commands ###
